### ISSUE TITLE
Problems with PVC Storage Class in Kubeshark on a AKS cluster

### ISSUE THREAD

**Issue by Jarzamendia** [kubeshark/kubeshark#1340] opened 2023-04-25 00:27 UTC
**Describe the bug**
When running the Kubeshark v40.0 the pods wont start because of a PVC with a bad storage class.

**Provide more information**
Running in AKS v1.25.6.
Kubeshark in V40.0

**To Reproduce**
1. Run `kubeshark tap`
2. Run `kubectl get pvc -n kubeshark`
4. See PCV in pending status

**Expected behavior**
The PVC should use a default storage class. 

**Screenshots**
![image](https://user-images.githubusercontent.com/14064715/234143864-841d614b-6290-4017-937e-615ce8216d12.png)

**Additional context**
If possible, we can not set the storage class in the manifests. With no stg class, the PVC takes the default storage class from the cluster.

**Comment by hubert-he** [comment] 2023-04-25 01:29
they provide command option, you can set yourself sc. for instance,  kubeshark tap -r deploy.hubert/kubeshark/ --storageclass "local-storage"

**Comment by bastibrunner** [comment] 2023-04-28 11:06
I'm having the same issue. Unfortunately changing the storage class doesn't work for me, as I don't have a storage plugin available in my cluster that supports ReadWriteMany. I guess this could be a problem for many users.

**Comment by alongir** [comment] 2023-05-02 22:33
In V40.0 we've introduced the volume persistency feature to ensure no data is lost. From the reactions, we understand the current solution doesn't support all K8s distributions. Solution is in the works. We'll report asap, once a solution is available. As our workload is relatively high at this point, this is a matter of ~ 1-2 weeks.

**Comment by mertyildiran** [comment] 2023-05-03 22:46
> I'm having the same issue. Unfortunately changing the storage class doesn't work for me, as I don't have a storage plugin available in my cluster that supports ReadWriteMany. I guess this could be a problem for many users.

Please see: https://github.com/kubeshark/kubeshark/issues/1337#issuecomment-1519172816

**Comment by mertyildiran** [comment] 2023-05-03 22:48
Duplicate of https://github.com/kubeshark/kubeshark/issues/1337

**Comment by mertyildiran** [comment] 2023-05-11 10:00
We have made the PVC optional (disabled by default) as of [the release 40.2](https://github.com/kubeshark/kubeshark/releases/tag/40.2)

The `persistentstorage` field in both `config.yaml` and `values.yaml` (Helm) can be set to `true` to enable the PVC.

The flag `--persistentstorage` of `tap` command enables the PVC.

**Closed by mertyildiran** 2023-05-11 10:00 UTC
Labels: duplicate, helm
