### ISSUE TITLE
Targeting 0 pods in UI/console, but kubeshark tap lists pods

### ISSUE THREAD

**Issue by wallagib** [kubeshark/kubeshark#1330] opened 2023-04-06 15:16 UTC
**Describe the bug**
The bug is, when running `kubeshark tap "(api*)" -A`, the CLI lists out one or multiple pods that match the regex, but when the UI is automatically opened, it is stuck saying "Targeting 0 pods". Also, the counter for TCP/UDP streams continually increases at the bottom.

I was on 38.5 and had no issues. Someone else had this problem, and I upgraded to 39.5, and **sporadically** reproduced the issue. I downgraded to 38.5 and the issue seems to have gone away.

**Provide more information**
GKE, 1 node.

**To Reproduce**
1. Run `kubeshark tap <regex> -A`
2. Confirm that above output says at least one pod is targeted.
3. Go to the UI and observe Targeting 0 pods.

**Expected behavior**
To see traffic, either DNS or user-initiated HTTP, in the UI for the pods being observed.

**Logs**
```
$ kubeshark --debug tap "(api*)" -A
2023-04-06T11:06:52-04:00 INF versionCheck.go:23 > Checking for a newer version...
2023-04-06T11:06:52-04:00 DBG config.go:79 > Init config is finished. config={"Config":{"Regenerate":false},"DumpLogs":false,"HeadlessMode":false,"Kube":{"ConfigPathStr":"","Context":""},"License":"","Logs":{"FileStr":""},"ResourceLabels":{},"Scripting":{"Env":null,"Source":"","WatchScripts":true},"Tap":{"AllNamespaces":true,"Debug":true,"Docker":{"ImagePullPolicy":"Always","ImagePullSecrets":null,"Registry":"docker.io/kubeshark","Tag":"latest"},"DryRun":false,"Namespaces":null,"PacketCapture":"libpcap","Pcap":"","PodRegexStr":".*","Proxy":{"Front":{"DstPort":80,"SrcPort":8899},"Host":"127.0.0.1","Hub":{"DstPort":80,"SrcPort":8898},"Worker":{"DstPort":8897,"SrcPort":8897}},"Resources":{"Hub":{"CpuLimit":"750m","CpuRequests":"50m","MemoryLimit":"1Gi","MemoryRequests":"50Mi"},"Worker":{"CpuLimit":"750m","CpuRequests":"50m","MemoryLimit":"1Gi","MemoryRequests":"50Mi"}},"SelfNamespace":"kubeshark","ServiceMesh":true,"StorageLimit":"200MB","Tls":true}}
2023-04-06T11:06:52-04:00 INF tapRunner.go:53 > Using Docker: registry=docker.io/kubeshark/ tag=latest
2023-04-06T11:06:52-04:00 INF tapRunner.go:61 > Kubeshark will store the traffic up to a limit (per node). Oldest TCP streams will be removed once the limit is reached. limit=200MB
2023-04-06T11:06:52-04:00 DBG provider.go:83 > K8s client config. api-path= host=https://<IP> user-agent=
2023-04-06T11:06:52-04:00 INF common.go:69 > Using kubeconfig: path=/Users/X/Documents/kubeconfig
2023-04-06T11:06:53-04:00 DBG versionCheck.go:38 > Fetched the latest release: elapsed-time=411.2225 local-version=39.5 upstream-version=39.5
2023-04-06T11:06:53-04:00 INF tapRunner.go:82 > Targeting pods in: namespaces=[""]
2023-04-06T11:06:53-04:00 INF tapRunner.go:142 > Targeted pod: api-X-5d4df596d7-jxg6b
2023-04-06T11:06:53-04:00 INF tapRunner.go:142 > Targeted pod: X-api-7bd767cf84-wwcnw
2023-04-06T11:06:53-04:00 INF tapRunner.go:142 > Targeted pod: X-api-87b56b48c-5fsmr
2023-04-06T11:06:53-04:00 INF tapRunner.go:92 > Waiting for the creation of Kubeshark resources...
2023-04-06T11:06:54-04:00 INF createResources.go:111 > Successfully created a pod. pod=kubeshark-hub
2023-04-06T11:06:54-04:00 INF createResources.go:123 > Successfully created a pod. pod=kubeshark-front
2023-04-06T11:06:54-04:00 INF createResources.go:72 > Successfully created a service. service=kubeshark-hub
2023-04-06T11:06:55-04:00 INF createResources.go:79 > Successfully created a service. service=kubeshark-front
2023-04-06T11:06:55-04:00 DBG wait.go:13 > Waiting to finish...
2023-04-06T11:06:55-04:00 INF tapRunner.go:173 > Added: pod=kubeshark-hub
2023-04-06T11:06:55-04:00 DBG tapRunner.go:369 > Watching events. event=kubeshark-hub.175360e3220ffdb0 kind=Pod name=kubeshark-hub note="Successfully assigned kubeshark/kubeshark-hub to <cluster>-0c79daba-zmlb" pod=kubeshark-hub reason=Scheduled
2023-04-06T11:06:55-04:00 INF tapRunner.go:264 > Added: pod=kubeshark-front
2023-04-06T11:06:55-04:00 DBG tapRunner.go:369 > Watching events. event=kubeshark-hub.175360e359ce4d2c kind=Pod name=kubeshark-hub note="Pulling image \"docker.io/kubeshark/hub:latest\"" pod=kubeshark-hub reason=Pulling
2023-04-06T11:06:56-04:00 DBG tapRunner.go:369 > Watching events. event=kubeshark-hub.175360e38bf8d885 kind=Pod name=kubeshark-hub note="Successfully pulled image \"docker.io/kubeshark/hub:latest\" in 841.59678ms" pod=kubeshark-hub reason=Pulled
2023-04-06T11:06:56-04:00 DBG tapRunner.go:369 > Watching events. event=kubeshark-hub.175360e38dc0c474 kind=Pod name=kubeshark-hub note="Created container kubeshark-hub" pod=kubeshark-hub reason=Created
2023-04-06T11:06:56-04:00 DBG tapRunner.go:369 > Watching events. event=kubeshark-hub.175360e392f5982e kind=Pod name=kubeshark-hub note="Started container kubeshark-hub" pod=kubeshark-hub reason=Started
2023-04-06T11:06:57-04:00 DBG tapRunner.go:190 > Watching pod. containers-statuses=[{"containerID":"containerd://c6ef91ccad6e899a09ada843f0615b5c4b43bd24df7f87250708060f24917d10","image":"docker.io/kubeshark/hub:latest","imageID":"docker.io/kubeshark/hub@sha256:c64e435a9d3ca3bf17acb01f16c389606e37ecb3888e6046ab5e578d932a3de8","lastState":{},"name":"kubeshark-hub","ready":true,"restartCount":0,"started":true,"state":{"running":{"startedAt":"2023-04-06T15:06:56Z"}}}] phase=Running pod=kubeshark-hub
2023-04-06T11:06:57-04:00 INF proxy.go:29 > Starting proxy... namespace=kubeshark service=kubeshark-hub src-port=8898
2023-04-06T11:06:57-04:00 DBG hub.go:45 > Connection test passed successfully. url=http://localhost:8898
2023-04-06T11:06:57-04:00 INF workers.go:33 > Creating the worker DaemonSet...
2023-04-06T11:06:57-04:00 DBG provider.go:648 > Applying worker DaemonSets. daemonset-name=kubeshark-worker-daemon-set image=docker.io/kubeshark/worker:latest namespace=kubeshark pod=kubeshark-worker
2023-04-06T11:06:57-04:00 INF workers.go:52 > Successfully created the worker DaemonSet.
2023-04-06T11:06:57-04:00 INF tapRunner.go:436 > Waiting for worker containers...
2023-04-06T11:06:58-04:00 DBG tapRunner.go:281 > Watching pod. containers-statuses=[{"containerID":"containerd://471f7262e065b21ee993740d222e097c404caaa0f8fadec508fa199264a6584d","image":"docker.io/kubeshark/front:latest","imageID":"docker.io/kubeshark/front@sha256:2c091e31222ede3a8d605af95f8a80467f5ab66454035178b6145de7193dd538","lastState":{},"name":"kubeshark-front","ready":false,"restartCount":0,"started":true,"state":{"running":{"startedAt":"2023-04-06T15:06:57Z"}}}] phase=Running pod=kubeshark-front
2023-04-06T11:06:58-04:00 INF proxy.go:29 > Starting proxy... namespace=kubeshark service=kubeshark-front src-port=8899
2023-04-06T11:06:58-04:00 DBG hub.go:43 > Not ready yet! error="got response with status code: 503, body: {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"no endpoints available for service \\\"kubeshark-front:80\\\"\",\"reason\":\"ServiceUnavailable\",\"code\":503};" url=http://localhost:8899
2023-04-06T11:07:03-04:00 DBG hub.go:112 > Reported storage limit to Hub: limit=200000000
2023-04-06T11:07:03-04:00 DBG hub.go:145 > Reported pod regex to Hub: namespaces=[""] regex=(api*)
2023-04-06T11:07:03-04:00 DBG hub.go:344 > Reported POST scripts done to Hub.
2023-04-06T11:07:03-04:00 INF tapRunner.go:471 > Hub is available at: url=http://localhost:8898
2023-04-06T11:07:03-04:00 DBG hub.go:45 > Connection test passed successfully. url=http://localhost:8899
2023-04-06T11:07:03-04:00 INF tapRunner.go:492 > Kubeshark is available at: url=http://localhost:8899
2023-04-06T11:07:03-04:00 DBG tapRunner.go:281 > Watching pod. containers-statuses=[{"containerID":"containerd://471f7262e065b21ee993740d222e097c404caaa0f8fadec508fa199264a6584d","image":"docker.io/kubeshark/front:latest","imageID":"docker.io/kubeshark/front@sha256:2c091e31222ede3a8d605af95f8a80467f5ab66454035178b6145de7193dd538","lastState":{},"name":"kubeshark-front","ready":true,"restartCount":0,"started":true,"state":{"running":{"startedAt":"2023-04-06T15:06:57Z"}}}] phase=Running pod=kubeshark-front
```
**Screenshots**
<img width="936" alt="image" src="https://user-images.githubusercontent.com/102536477/230422415-823b3a6d-ce4f-4b05-80d6-8b671a773d79.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Web Browser: Google Chrome

**Additional context**

**Comment by mertyildiran** [comment] 2023-04-06 19:47
@wallagib is it an issue specific to the regex? Like if you do `kubeshark tap -A` for example, do you see the all pods correctly targeted in the UI?

**Comment by wallagib** [comment] 2023-04-06 19:59
I haven't tried that, but we did try '.*' as well as some other pod-specific ones. I'll give it a try later and see if anything is different

**Comment by RouxAntoine** [comment] 2023-04-07 10:21
i notice the same since yesterday.  I use kubeshark setup from brew (version 39.5 `2023-04-07T12:18:10+02:00 WRN versionCheck.go:48 > There is a new release! 0.0 -> 39.5 run`).

kubeshark-worker contained some error :

```
2023-04-07T10:18:45Z DBG assemblers/tcp_assembler.go:103 > Packets seen: count=49000
2023-04-07T10:18:45Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:40386->10250: Packet rejected by OptionChecker: 28752 > receiveWindow(512)
2023-04-07T10:18:45Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:50512->6443: Packet rejected by OptionChecker: 1492079 > receiveWindow(512)
2023-04-07T10:18:45Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:50512->6443: Packet rejected by OptionChecker: 42770 > receiveWindow(512)
2023-04-07T10:18:45Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:40386->10250: Packet rejected by OptionChecker: 28752 > receiveWindow(512)
2023-04-07T10:18:45Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:40386->10250: Packet rejected by OptionChecker: 28800 > receiveWindow(512)
2023-04-07T10:18:45Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:50512->6443: Packet rejected by OptionChecker: 1499554 > receiveWindow(512)
2023-04-07T10:18:45Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:40386->10250: Packet rejected by OptionChecker: 28800 > receiveWindow(512)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:50512->6443: Packet rejected by OptionChecker: 1503797 > receiveWindow(512)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:50512->6443: Packet rejected by OptionChecker: 42840 > receiveWindow(512)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:50512->6443: Packet rejected by OptionChecker: 42840 > receiveWindow(512)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:40386->10250: Packet rejected by OptionChecker: 28800 > receiveWindow(512)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:40386->10250: Packet rejected by OptionChecker: 28848 > receiveWindow(512)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:50512->6443: Packet rejected by OptionChecker: 1512634 > receiveWindow(512)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:40386->10250: Packet rejected by OptionChecker: 28848 > receiveWindow(512)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:50512->6443: Packet rejected by OptionChecker: 1522054 > receiveWindow(512)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:50512->6443: Packet rejected by OptionChecker: 1523475 > receiveWindow(512)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:50512->6443: Packet rejected by OptionChecker: 42910 > receiveWindow(512)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:50512->6443: Packet rejected by OptionChecker: 42910 > receiveWindow(512)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:40386->10250: Packet rejected by OptionChecker: 28848 > receiveWindow(512)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:50512->6443: Packet rejected by OptionChecker: 1523745 > receiveWindow(512)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:40386->10250: Packet rejected by OptionChecker: 28848 > receiveWindow(512)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:50512->6443: Packet rejected by OptionChecker: 1524264 > receiveWindow(512)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:50512->6443: Packet rejected by OptionChecker: 42980 > receiveWindow(512)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 100.66.168.10->10.1.1.7:54436->6443: Packet rejected by OptionChecker: 6140 > mss (1240)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 100.66.168.10->10.1.1.7:54436->6443: Packet rejected by OptionChecker: 6140 > mss (1240)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 100.66.168.10->10.1.1.7:54436->6443: Packet rejected by OptionChecker: 7368 > mss (1240)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 100.66.168.10->10.1.1.7:54436->6443: Packet rejected by OptionChecker: 7368 > mss (1240)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 100.66.168.10->10.1.1.7:54436->6443: Packet rejected by OptionChecker: 8596 > mss (1240)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 100.66.168.10->10.1.1.7:54436->6443: Packet rejected by OptionChecker: 8596 > mss (1240)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 100.66.168.10->10.1.1.7:54436->6443: Packet rejected by OptionChecker: 3257 > mss (1240)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 127.0.0.1->127.0.0.1:40386->10250: Packet rejected by OptionChecker: 28896 > receiveWindow(512)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 10.42.0.1->10.42.0.24:48072->9000: Packet rejected by OptionChecker: Re-emitted packet (diff:-119,seq:2277169303,rev-ack:2277169422)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 10.42.0.1->10.42.0.24:48070->9000: Packet rejected by OptionChecker: Re-emitted packet (diff:-119,seq:3161110028,rev-ack:3161110147)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 10.42.0.1->10.42.0.24:48070->9000: Packet rejected by OptionChecker: Re-emitted packet (diff:-439,seq:2165349303,rev-ack:2165349742)
2023-04-07T10:18:46Z ERR diagnose/errors_map.go:56 > OptionChecker-rejection: 10.42.0.1->10.42.0.24:48072->9000: Packet rejected by OptionChecker: Re-emitted packet (diff:-439,seq:1875819754,rev-ack:1875820193)
2023-04-07T10:18:46Z DBG assemblers/dns_factory.go:56 > Dumping DNS stream: file=data/pcaps/000000000034_udp.pcap
2023-04-07T10:18:46Z DBG server/controllers/socket.go:101 > Reading: pcap=000000000034_udp.pcap
2023-04-07T10:18:46Z ERR server/controllers/socket.go:107 > Failed to create packet source! error="PCAP OpenOffline error: truncated dump file; tried to read 4 file header bytes, only got 0" pcap=000000000034_udp.pcap
```

run command is `kubeshark tap -A --debug`

work with 38.5 too.

**Comment by mertyildiran** [comment] 2023-04-09 21:12
@wallagib I was only able to reproduce a delayed targeting and not a permanent "Targeting 0 pods". I have pushed a fix that might possibly resolve this issue. Could you please try it again? No need to update the CLI.

**Comment by mertyildiran** [comment] 2023-04-09 21:14
@RouxAntoine those error logs are sourced from the packet capture and they are related to pod targeting. Maybe we should set their log level to `DBG`.

**Comment by mertyildiran** [comment] 2023-04-23 22:52
Closing because of inactivity.

**Closed by mertyildiran** 2023-04-23 22:52 UTC
Labels: needs-triage
