### ISSUE TITLE
workers are down 

### ISSUE THREAD

**Issue by ThorSiv** [kubeshark/kubeshark#1299] opened 2023-01-16 05:52 UTC
when I run ```kubeshark tap -A --tls```, just a moment later ,the web-ui went to wrong like picture below: 
![image](https://user-images.githubusercontent.com/16603602/212607009-199cb7a2-d987-4257-a160-1343c60d9f20.png)
Here is hub logs:
![image](https://user-images.githubusercontent.com/16603602/212607308-2ba1ede7-8d20-4c57-9bc2-eb566df92623.png)
At the first ,I think workers need more cpu or memory.So I added some configuration:
```tap:
    resources:
        worker:
            cpu-limit: 1000m
            memory-limit: 1Gi
            cpu-requests: 50m
            memory-requests: 50Mi
        hub:
            cpu-limit: 1000m
            memory-limit: 1Gi
            cpu-requests: 50m
            memory-requests: 50Mi
```
But This didn't work .

**Comment by mertyildiran** [comment] 2023-01-17 23:34
@ThorSiv the issue is fixed with https://github.com/kubeshark/hub/commit/1a548c167735504518424a83d54d34576614c38b

**Closed by mertyildiran** 2023-01-17 23:34 UTC
Labels: bug
