### ISSUE TITLE
39.6 version can't set the right namespace

### ISSUE THREAD

**Issue by woodliu** [kubeshark/kubeshark#1335] opened 2023-04-19 03:01 UTC
**Describe the bug**

**Provide more information**
Running on AKS

**To Reproduce**
Just run `kubeshark tap -n xxx `with version 39.6

**Expected behavior**
Not as expected, and because so many packets it collects, it works very slow.

**Logs**

**Screenshots**
Version 39.6, you can see the `namespaces` section is nil, and kubeshark will collect the pod in multi-namespaces.
![image](https://user-images.githubusercontent.com/9976943/232954746-647fe00e-bcc7-4bbf-9e30-d1cb9bea084b.png)

Version 39.5, you can see it can set the correct namespace
![image](https://user-images.githubusercontent.com/9976943/232955445-5432b2d1-32a7-4ffc-a29a-e9615fe1c6f4.png)

**Desktop (please complete the following information):**
 - OS: MAC M1

**Additional context**
no

**Comment by alongir** [comment] 2023-04-19 15:34
@woodliu - thanks and good catch. I confirm I see this behavior.

**Comment by alongir** [comment] 2023-04-21 21:02
@woodliu Issues was fixed in V4.0. Kindly not the following:
1. No need to use `-A` anymore as the default `tap` behavior is listen to all namespaces.
2. If you are using a configuration file, please run: `kubeshark config -r` to update the config file to support the new release.

Other than that, if you use: 'kubeshark tap -n <namespace>`, Kubesahrk will tap that namespace.

**Comment by mertyildiran** [comment] 2023-04-23 21:58
@woodliu the issue is introduced with [this change](https://github.com/kubeshark/kubeshark/commit/c42481deb8c6040c9b4dea1f4f5adc226d9220c0#diff-103fd39bd0f52c0d4e4defb2a723032497f47b98a7e5f339bdd85cb080e833d9L77-R77) for making the Helm chart and resulting Kubernetes manifests to make Kubeshark target all namespaces by default.

The issue fixed by the removal of `-A` flag: https://github.com/kubeshark/kubeshark/commit/686dd5fba12ef3d72caac1244fc255729b6da7d5

`kubeshark tap` targets all namespaces

`kubeshark tap -n <LIST_OF_NAMESPACES>` targets a namespace or a list of comma-separated namespaces.

Please try [the release `40.0`](https://github.com/kubeshark/kubeshark/releases/tag/40.0)

**Closed by mertyildiran** 2023-04-23 21:58 UTC
Labels: bug, CLI
